# Generated by Django 3.2.2 on 2021-05-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRole', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
