# Generated by Django 3.2.2 on 2021-05-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminRole', '0001_initial'),
        ('userRole', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='advisors',
            field=models.ManyToManyField(to='adminRole.Advisor'),
        ),
    ]
